import type {Metadata} from "next";
import "./globals.css";
import {ScopedStateProvider} from "@/scopedstate";
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="pt-br">
            <body className={`antialiased`}>
                <ScopedStateProvider>
                    {children}
                </ScopedStateProvider>
            </body>
        </html>
    );
}
